---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Binary Build"

on:
  workflow_dispatch:
    inputs:
      force:
        required: false
        default: true
        type: boolean
        description: Force rebuild
  release:
    types: [created]
    secrets:
      BOT_APP_ID:
        description: The App ID of the GitHub App
        required: true
      BOT_APP_PRIVATE_KEY:
        description: The private key of the GitHub App
        required: true

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: "${{ steps.app-token.outputs.token }}"
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.13.linux-amd64.tar.gz"
          project_path: "./cmd/transmission-exporter"
          binary_name: "transmission-exporter"
          compress_assets: OFF
        env:
          GO111MODULE: on
          CGO_ENABLED: 0
          # extra_files: LICENSE README.md
